alias g='gedit'
alias mtargz='tar -xzf'
alias mtarbz='tar -xjf'
alias tips='(g ~/Docs/tips ~/Docs/key_combinations) &'
alias gst='git status --untracked-files=no'
alias gstt='git status'
alias gdf='git diff'
alias gco='git chechout'
alias gbr='git branch'
alias gad='git add'
